databank-copy3/config/routes.rb
Rails.application.routes.draw do

get 'index' => 'shop_lists#index'
get 'setting' => 'shop_lists#setting'
get 'finish' => 'shop_lists#finish'

patch 'shop_lists/:shop_list_id/performances' => 'performances#create'

resources :shop_lists do
    resources :performances, only: [:create,:new,:show]
    member do
    get 'view'
    end
    member do
    get 'csvprint'
    end
    member do
    get 'csvprint1'
    end
    member do
    get 'csvprint2'
    end
end

end

databank-copy3/app/models/performance.rb
class Performance < ActiveRecord::Base
belongs_to :shop_list

validates :day, presence: true
validates :wimax, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :uqm, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}

validates :ym_wifi, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :sb_net, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :sb_wifi, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :au_net, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :au_wifi, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :do_net, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :sb_phone, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :au_phone, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :do_phone, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}
validates :ym_phone, presence: true,numericality: { only_integer: true,greater_than_or_equal_to: 0}

end

databank-copy3/app/models/shop_list.rb
class ShopList < ActiveRecord::Base
  has_many :performances
end

databank-copy3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with :name => 'admin', :password => 'hogehoge' if Rails.env == "production"



  #production or development
  #上記BASIC認証の作成
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

databank-copy3/app/controllers/performances_controller.rb
class PerformancesController < ApplicationController

  before_action :check_day, only:[:create]


    def new
      @shop_list = ShopList.find(params[:shop_list_id])
      # @performance = Performance.find_by(day:'2017-01-01',shop_list_id:'1')
      @performance = Performance.new
     end

    def create
#@pf
      @pf = Performance.create(create_params)
      @shop_list = ShopList.find(params[:shop_list_id])

      if @pf.save

      @mail = Notice.sendmail_confirm(@shop_list).deliver_now
      redirect_to controller: :shop_lists, action: :finish
    else
     # redirect_to controller: :shop_lists, action: :index
     render :_form
    end

    end

    def check_day
      if @pf = Performance.find_by(check)
        # binding.pry
         @pf.update_attributes(create_params2)
         if @pf.save
         @shop_list = ShopList.find(params[:shop_list_id])
         @mail = Notice.sendmail_confirm(@shop_list).deliver_now
         redirect_to controller: :shop_lists, action: :finish
       else
        render :_form
        # redirect_to controller: :shop_lists, action: :index
       end
    end
    end

    private
    def check
      params.require(:performance).permit(:day).merge(shop_list_id: params[:shop_list_id])
    end

  private
  def create_params
    params.require(:performance).permit(:day, :wimax, :uqm, :ym_wifi, :sb_net, :sb_wifi, :au_net, :au_wifi, :do_net, :sb_phone, :au_phone, :do_phone, :ym_phone).merge(shop_list_id: params[:shop_list_id])
  end

  private
  def create_params2
    params.require(:performance).permit(:wimax, :uqm, :ym_wifi, :sb_net, :sb_wifi, :au_net, :au_wifi, :do_net, :sb_phone, :au_phone, :do_phone, :ym_phone)
  end


end

databank-copy3/app/controllers/shop_lists_controller.rb
class ShopListsController < ApplicationController
    # before_action :check_btn, only:[:csvprint]

    def index
      @shop_lists = ShopList.all
    end

    def show
      @shop_list = ShopList.find(params[:id])

      # binding.pry
      @performances = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:wimax).sum(:wimax)
      # @performances = Performance.where(day: Time.now.all_month).select(:wimax).sum(:wimax)
      @performances2 = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:uqm).sum(:uqm)
      # @performances2 = Performance.where(day: Time.now.all_month).select(:uqm).sum(:uqm)
      @ym_wifi = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:ym_wifi).sum(:ym_wifi)
      @sb_net = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:sb_net).sum(:sb_net)
      @sb_wifi = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:sb_wifi).sum(:sb_wifi)
      @au_net = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:au_net).sum(:au_net)
      @au_wifi = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:au_wifi).sum(:au_wifi)
      @do_net = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:do_net).sum(:do_net)

      @sb_phone = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:sb_phone).sum(:sb_phone)
      @au_phone = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:au_phone).sum(:au_phone)
      @do_phone = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:do_phone).sum(:do_phone)
      @ym_phone = Performance.where(day: Time.now.all_month,shop_list_id: params[:id]).select(:do_phone).sum(:do_phone)

      #実績合計の数字のみ帰ってくる。
      # @performances = Performance.where(day: Time.now.all_month).select(:wimax)
      # @performances = Performance.where(day: Time.now.all_month).pluck(:wimax,:uqm)
      @net_share =[["wimax",@performances],["YMデータ",@ym_wifi],["SB光",@sb_net],["SB-Air",@sb_wifi],["au光",@au_net],["auデータ",@au_wifi],["docomo光",@do_net]]
      @sp_share =[["uqmobile",@performances2],["SBスマホ",@sb_phone],["auスマホ",@au_phone],["docomoスマホ",@do_phone],["ymスマホ",@ym_phone]]
    end


  def new
    @pf_csv = Performance.all
  end

  def view
    @id=params[:id]
    @shop_list = ShopList.find(params[:id])
    @time = Time.now.all_month
    @pf = Performance.where(shop_list_id: @id,day: @time)
  end

  def finish
  end

  def setting

    @time = Time.now.all_month

    @ranking_net_keys = Performance.where(day: @time).order(wimax: :desc).group(:shop_list_id).sum(:wimax).keys
    @ranking_net_values = Performance.where(day: @time).order(wimax: :desc).group(:shop_list_id).sum(:wimax).values

    @ranking_phone_keys = Performance.where(day: @time).order(uqm: :desc).group(:shop_list_id).sum(:uqm).keys
    @ranking_phone_values = Performance.where(day: @time).order(uqm: :desc).group(:shop_list_id).sum(:uqm).values

    @mail = Notice.sendmail_setting(@ranking_net_keys,@ranking_net_values,@ranking_phone_keys,@ranking_phone_values).deliver_now

  end

  def csvprint
    @id=params[:id]
    @time = Time.now.all_month
    @pf = Performance.where(shop_list_id: @id,day: @time)

  @shop_name = ShopList.find(@id).name
  respond_to do |format|
  format.csv do
  send_data render_to_string, filename: "#{@shop_name}#{Time.now.strftime("%Y%m%d")}.csv", type: :csv
  end
  end


end

def csvprint1
  @id=params[:id]

  @time1= 1.months.ago(Time.now).all_month
  @pf = Performance.where(shop_list_id: @id,day: @time1)
  @time= 1.months.ago(Time.now)
  @shop_name = ShopList.find(@id).name
  respond_to do |format|
  format.csv do
  send_data render_to_string, filename: "#{@shop_name}#{@time.strftime("%Y%m")}.csv", type: :csv
  end
  end
end

def csvprint2
    @id=params[:id]

    @time2= 2.months.ago(Time.now).all_month
    @pf = Performance.where(shop_list_id: @id,day: @time2)

    @time= 2.months.ago(Time.now)
    @shop_name = ShopList.find(@id).name
    respond_to do |format|
    format.csv do
    send_data render_to_string, filename: "#{@shop_name}#{@time.strftime("%Y%m")}.csv", type: :csv
end
end
end

end

databank-copy3/app/helpers/application_helper.rb
module ApplicationHelper
end

databank-copy3/app/helpers/performances_helper.rb
module PerformancesHelper
end

databank-copy3/app/helpers/shop_lists_helper.rb
module ShopListsHelper
end

databank-copy3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Databank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <!-- チャートを作るためのchartkickの記述。 -->
<meta name="viewport" content="width=device-width,initial-scale=1">
<!-- レスポンシブルデザイン -->
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/index">実績管理システム</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

       <ul class="nav navbar-nav navbar-right">
        <li><a href="/index">TOP</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">他店実績 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/shop_lists/1">A店【実績確認】</a></li>
            <li><a href="/shop_lists/2">B店【実績確認】</a></li>
            <li><a href="/shop_lists/3">C店【実績確認】</a></li>
            <li><a href="/shop_lists/4">D店【実績確認】</a></li>
            <li><a href="/shop_lists/5">E店【実績確認】</a></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- navar -->
<div class=“container”>
<%= yield %>
</div>

</body>
</html>

databank-copy3/app/views/notice/sendmail_confirm.text.erb
<%= @shop_list.name %>

日時:<%= @pf.day %>

-------------
wimax:<%= @pf.wimax %> 件

uqm:<%= @pf.uqm %>件
--------------
YMデータ:<%= @pf.ym_wifi %>件

SB光:<%= @pf.sb_net %>件

SBAir:<%= @pf.sb_wifi %>件

au光:<%= @pf.au_net %>件

auデータ:<%= @pf.au_wifi %>件

do光:<%= @pf.do_net %>件
--------------
YMスマホ:<%= @pf.ym_phone %>件

SBスマホ:<%= @pf.sb_phone %>件

auスマホ:<%= @pf.au_phone %>件

docomoスマホ:<%= @pf.do_phone %>件

上記、内容にて登録完了いたしました。

databank-copy3/app/views/notice/sendmail_setting.html.erb
<h1>ランキングメール</h1>

<% a= 1 %>

<h2> WiMAX実績 <h2>
<% @ranking_net_keys.zip(@ranking_net_values).each do |ranking_net_key,ranking_net_value| %>


<div>
<%= a %> 位
<%= ShopList.find(ranking_net_key).name %>
<%= ranking_net_value %>件
<% a +=1 %>
</div>

<% end %>

<% b = 1 %>

<h2> WiMAX実績 <h2>
<% @ranking_phone_keys.zip(@ranking_phone_values).each do |ranking_phone_key,ranking_phone_value| %>


<div>
<%= b %> 位
<%= ShopList.find(ranking_phone_key).name %>
<%= ranking_phone_value %>件
<% a +=1 %>
</div>

<% end %>

databank-copy3/app/views/notice/sendmail_setting.text.erb
<h1>ランキングメール</h1>

<% a= 1 %>

<h2> WiMAX実績 <h2>
<% @ranking_net_keys.zip(@ranking_net_values).each do |ranking_net_key,ranking_net_value| %>


<div>
<%= a %> 位
<%= ShopList.find(ranking_net_key).name %>
<%= ranking_net_value %>件
<% a +=1 %>
</div>

<% end %>

<% b = 1 %>

<h2> WiMAX実績 <h2>
<% @ranking_phone_keys.zip(@ranking_phone_values).each do |ranking_phone_key,ranking_phone_value| %>


<div>
<%= b %> 位
<%= ShopList.find(ranking_phone_key).name %>
<%= ranking_phone_value %>件
<% a +=1 %>
</div>

<% end %>

databank-copy3/app/views/performances/_form.html.erb
<% if @pf.errors.any? %>
<div id="error_explanation" class ="form-control:focus alert alert-danger">


<h3><%= @pf.errors.count %>件の入力エラーがあります。</h3>

   <ul>
  <% @pf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
</div>
<a href="javascript:history.back()">[戻る]</a>
<% end %>

databank-copy3/app/views/performances/new.html.erb
<div align="center">
<p><%= @shop_list.name %>~新規実績登録~</p>
</div>




<div class="row form">

<div class = "col-xs-8 col-md-6">

    <%= form_for @performance,url:{action: "create"} do |f| %>

<ul>
    <div class="form-group"><%= f.date_field :day, placeholder: "日付", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :wimax, placeholder: "wimax実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :uqm, placeholder: "UQM実績", class: "form-control" %></div>

    <div class="form-group"><%= f.number_field :ym_wifi, placeholder: "YMデータ実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :sb_net, placeholder: "SB光実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :sb_wifi, placeholder: "SBAir実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :au_net, placeholder: "au光実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :au_wifi, placeholder: "auデータ実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :do_net, placeholder: "docomo光実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :ym_phone, placeholder: "ymスマホ実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :sb_phone, placeholder: "SBスマホ実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :au_phone, placeholder: "auスマホ実績", class: "form-control" %></div>
    <div class="form-group"><%= f.number_field :do_phone, placeholder: "docomoスマホ実績", class: "form-control" %></div>
</ul>

      <div align="right"><%= f.submit "送信", class: "btn btn-primary withripple" %></div>

    <% end %>

</div>

</div>

databank-copy3/app/views/shop_lists/finish.html.erb
<h1>登録完了致しました。</h1>


<h4><a href="/index">TOPへ</a></h4>

databank-copy3/app/views/shop_lists/index.html.erb
<h3  align="center">メニュー選択</h3>

<div class="row" >
<div class="col-xs-12 col-sm-12 col-md-12", align="center">
<!-- <div class="contents" > -->
<% @shop_lists.each do |shop_list| %>

<h2>【<%= shop_list.name %>】</h2>

<h2><%= link_to '新規実績登録', new_shop_list_performance_path(shop_list.id), class: 'btn btn-default list-style:none' %><%= link_to '実績確認', shop_list_path(shop_list.id), class: 'btn btn-default list-style:none' %></h2>


<% end %>
<!-- </div> -->
</div>

</div>

databank-copy3/app/views/shop_lists/setting.html.erb
<h1>ランキングメール配信しました。</h1>

<% a= 1 %>

<h2> WiMAX実績 <h2>
<% @ranking_net_keys.zip(@ranking_net_values).each do |ranking_net_key,ranking_net_value| %>


<div>
<%= a %> 位
<%= ShopList.find(ranking_net_key).name %>
<%= ranking_net_value %>件
<% a +=1 %>
</div>

<% end %>

<% b = 1 %>

<h2> WiMAX実績 <h2>
<% @ranking_phone_keys.zip(@ranking_phone_values).each do |ranking_phone_key,ranking_phone_value| %>


<div>
<%= b %> 位
<%= ShopList.find(ranking_phone_key).name %>
<%= ranking_phone_value %>件
<% a +=1 %>
</div>

<% end %>

databank-copy3/app/views/shop_lists/show.html.erb
<h1><%= @shop_list.name %>実績確認</h1>

<div class:="row">

<div class="col-xs-12 col-sm-6 col-md-8">
   <p><%= link_to "今月実績-CSV出力", csvprint_shop_list_path(format: :csv), class: "btn btn-primary btn-sm"%></p>
   <p><%= link_to "前月実績-CSV出力", csvprint1_shop_list_path(format: :csv), class: "btn btn-primary btn-sm"%></p>
   <p><%= link_to "前々月実績-CSV出力", csvprint2_shop_list_path(format: :csv), class: "btn btn-primary btn-sm"%></p>
   <p><%= link_to "HTML実績表示", view_shop_list_path, class: "btn btn-default btn-sm"%></p>
</div>


<div class="col-xs-12 col-sm-6 col-md-4">
<h4><%=Time.now.strftime("%Y/%-m/%-d") %>時点実績</h4>
<li>WiMAX実績:<%= @performances %>件</li>
<li>UQmobile実績:<%= @performances2 %>件</li>
</div>

</div>



<div class="row">
<div class="col-xs-12 col-sm-12 col-md-6">
<p>■スマートフォン店舗内シェア■<p>
<%= pie_chart @sp_share %>
</div>
<div class="col-xs-12 col-sm-12 col-md-6">
<p>■インターネット店舗内シェア■<p>
<%= pie_chart @net_share %>
</div>
</div>

databank-copy3/app/views/shop_lists/view.html.erb
<h2><%= @shop_list.name %><h2>
<p><%= Time.now.strftime("%Y/%-m/%-d") %>時点 実績<p>

<div class="row col-xs-11 col-sm-11 col-md-11">

<!-- <table> -->
<table border="1">
<thead>
<tr>

<% culumn = Performance.column_names %>
<% culumn_names = Performance.column_names %>
<%  list = ['id','shop_list_id','created_at','updated_at'] %>
<%  culumn_names.delete_if do |str| %>
<%  list.include?(str) %>
<%  end %>


<% culumn.each do |culumn| %>

<th><%= culumn %></th>
<% end %>


</tr>
</thead>

<!-- <tbody> -->
  <tr>
<% @pf.each do |pf| %>

  <% value = pf.attributes.values %>
  <% a = 0 %>
    <% value.each do |value| %>

      <% unless a == 0 || a == 2 || a == 5 || a == 6 %>
        <td><%= value %></td>
      <% end %>

      <% a +=1 %>
    <% end %>
  </tr>
<% end %>

<!-- </tbody> -->
</table>

</div>